
spring:
  datasource:
    # url 맨 뒤에 ?useSSL=false&allowPublicKeyRetrieval=true 를 추가하세요.
    url: jdbc:mysql://mutsa-db.c1uyey6aut42.ap-northeast-2.rds.amazonaws.com/mutsa_shopping?useSSL=false&allowPublicKeyRetrieval=true
    username: seoyoung0305
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080